color: yellow
fieldLayouts:
  7f568ebf-1ef9-4b3b-844a-689670135fe0:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-03-13T21:34:46+00:00'
            elementCondition: null
            fieldUid: 5fd391e7-5e9b-4552-9423-16102d2210cc # Heading
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 890dcf84-fa63-4443-aee1-0058523e7590
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-13T21:34:46+00:00'
            elementCondition: null
            fieldUid: 47ee7517-59aa-4532-a3c5-028ed325670d # Description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0d5328b7-613b-4d02-8231-c694170b38b4
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-13T21:34:46+00:00'
            elementCondition: null
            fieldUid: 6c899c98-0e37-4bb5-97df-5b1d53b40281 # Actions
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ae02b7a9-733b-48d9-84b7-4821587c306e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-13T21:34:46+00:00'
            elementCondition: null
            fieldUid: 73a7162d-b07e-405d-be78-96423e43ca89 # Images
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cd0615a0-2dd5-48b4-92c8-795928103feb
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4f74fb80-803e-48dc-84ef-34fa8eba5b63
        userCondition: null
handle: heroBanner
hasTitleField: false
icon: mask
name: 'Hero banner'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
