color: yellow
fieldLayouts:
  8fb87cd9-3787-4c07-af07-c95afa2bc5c5:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-03-13T23:11:48+00:00'
            elementCondition: null
            fieldUid: 5fd391e7-5e9b-4552-9423-16102d2210cc # Heading
            handle: highlightedText
            includeInCards: false
            instructions: null
            label: 'Highlighted text'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: eb6ed327-1f26-4e4d-bc30-faef48980609
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c7152a66-a2c6-4ff5-8f82-6dfa01b49d27
        userCondition: null
handle: highlightedText
hasTitleField: false
icon: text
name: 'Highlighted text'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
