color: yellow
fieldLayouts:
  5a4f7fcf-7401-4a8d-9c27-50abe95e3e96:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-03-13T23:13:01+00:00'
            elementCondition: null
            fieldUid: 5fd391e7-5e9b-4552-9423-16102d2210cc # Heading
            handle: subTitle
            includeInCards: false
            instructions: null
            label: 'Sub title'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b3e478af-1cfb-4477-be12-08cf53448ceb
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-13T23:12:12+00:00'
            elementCondition: null
            fieldUid: 825511a6-afc4-457c-a1bd-c476ab5d2e56 # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a9c23139-d423-42de-99b0-8e565396df95
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-13T23:12:12+00:00'
            elementCondition: null
            fieldUid: 485d659b-8c7c-48bc-ad83-f6f8b8b19b95 # Editor contents
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 60bc6b13-68c7-4f42-9864-503cfa5a0254
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: bcd32204-a4ee-4c66-8b98-08d3b831fc86
        userCondition: null
handle: inspirationContent
hasTitleField: false
icon: align-justify
name: 'Inspiration content'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
