color: yellow
fieldLayouts:
  aae596b2-f196-4c54-b550-cd43ad9b48d9:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-03-14T00:00:56+00:00'
            elementCondition: null
            fieldUid: 5fd391e7-5e9b-4552-9423-16102d2210cc # Heading
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9eab9ff9-f871-4714-b7e2-14dc6eecd027
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-14T00:00:56+00:00'
            elementCondition: null
            fieldUid: 1cc501c6-7465-41d2-a392-9870a0a59e48 # Events
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 687d963e-1dd2-4530-a0e4-ffaaef2ef1c1
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-14T01:07:49+00:00'
            elementCondition: null
            fieldUid: 75968ea4-3e1b-46d8-86ef-1757f6d6cee8 # Lightswitch
            handle: listAllEvents
            includeInCards: false
            instructions: null
            label: 'List all events'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4721bfa5-e6ff-4509-8955-aa45e5a79c16
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 768cd33c-37a6-46fa-8cd4-52f5b2dea284
        userCondition: null
handle: listOfEvents
hasTitleField: false
icon: calendar
name: 'List of events'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
