color: yellow
fieldLayouts:
  70f17126-7f9b-408c-8a62-1afab6f42ce4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-03-13T23:10:44+00:00'
            elementCondition: null
            fieldUid: 5fd391e7-5e9b-4552-9423-16102d2210cc # Heading
            handle: quote
            includeInCards: false
            instructions: null
            label: Quote
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fc6a7918-0089-4f87-b9a9-929c37825f1f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-13T23:11:07+00:00'
            elementCondition: null
            fieldUid: 5fd391e7-5e9b-4552-9423-16102d2210cc # Heading
            handle: authorName
            includeInCards: false
            instructions: null
            label: 'Author name'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 77c6a620-da05-48cc-9749-6236ddb2d19a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 25275ba3-a9af-4e1d-a02c-705558e9ee19
        userCondition: null
handle: quote
hasTitleField: false
icon: quote-left
name: Quote
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
