color: yellow
description: null
fieldLayouts:
  5cf34f64-90ca-4717-827f-7b9c9006d85f:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-08-12T07:54:10+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 7e24c944-815b-4e50-a3d5-0d05a4ec0c69
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-12T07:55:55+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 949a8b9b-ebc1-4490-82fb-9162319ab4f3
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9b563be5-baec-41ca-8391-fe24f226fe2b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-16T13:34:45+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 8e59ee11-3265-4986-b1a3-0886a40aa212 # Number of testimonials per view
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 43010adc-87e8-48f7-9988-254bbd17adc0
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: cacf4e3b-e81f-4e55-afc0-91e961492ad0
        userCondition: null
handle: testimonials
hasTitleField: true
icon: comment
name: Testimonials
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
