headingLevels:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
name: Simple
options:
  alignment:
    options:
      - left
      - right
toolbar:
  - heading
  - alignment
  - underline
  - strikethrough
  - bold
  - italic
  - '|'
  - bulletedList
  - numberedList
  - outdent
  - indent
  - '|'
  - link
  - insertImage
  - mediaEmbed
  - insertTable
  - sourceEditing
