defaultPlacement: end
fieldLayouts:
  52da76fe-0c2f-465b-af6f-80632e32a183:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-08-19T11:19:09+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: c6bdd6d1-7750-4a73-9136-a549d1f8320b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-19T11:19:09+00:00'
            elementCondition: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: verbb\navigation\fieldlayoutelements\NodeTypeElements
            uid: 3f676303-98c0-482c-8984-810605254c9c
            userCondition: null
            warning: null
          -
            attribute: newWindow
            dateAdded: '2025-08-19T11:19:09+00:00'
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            mandatory: false
            orientation: null
            providesThumbs: false
            requirable: true
            required: false
            tip: null
            translatable: false
            type: verbb\navigation\fieldlayoutelements\NewWindowField
            uid: a4415261-43db-4e99-b67e-c4f812c6bc6f
            userCondition: null
            warning: null
            width: 100
        name: Node
        uid: 446ab931-dd31-40b0-9779-39b3c4490c16
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            attribute: urlSuffix
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            autofocus: false
            class: null
            dateAdded: '2025-08-19T11:19:09+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            mandatory: false
            max: null
            maxlength: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: true
            required: false
            size: null
            step: null
            tip: null
            title: null
            translatable: false
            type: verbb\navigation\fieldlayoutelements\UrlSuffixField
            uid: db7139a4-41b2-46d4-87ae-3d0ac46226b2
            userCondition: null
            warning: null
            width: 100
          -
            attribute: classes
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            autofocus: false
            class: null
            dateAdded: '2025-08-19T11:19:09+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            mandatory: false
            max: null
            maxlength: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: true
            required: false
            size: null
            step: null
            tip: null
            title: null
            translatable: false
            type: verbb\navigation\fieldlayoutelements\ClassesField
            uid: df39a259-d688-40f5-9a81-262764a834d8
            userCondition: null
            warning: null
            width: 100
          -
            attribute: customAttributes
            dateAdded: '2025-08-19T11:19:09+00:00'
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            mandatory: false
            orientation: null
            providesThumbs: false
            requirable: true
            required: false
            tip: null
            translatable: false
            type: verbb\navigation\fieldlayoutelements\CustomAttributesField
            uid: cde5b815-caa1-460e-84d8-3a9fd6fa1f05
            userCondition: null
            warning: null
            width: 100
        name: Advanced
        uid: 1058e4c1-2a5b-477a-ac37-aff6962e30f8
        userCondition: null
handle: mainNavigation
instructions: ''
maxNodes: null
name: 'Main navigation'
permissions:
  craft\elements\Asset:
    enabled: '1'
    permissions: '*'
  craft\elements\Category:
    enabled: '1'
    permissions: '*'
  craft\elements\Entry:
    enabled: '1'
    permissions: '*'
  craft\elements\Tag:
    enabled: ''
    permissions: '*'
  verbb\navigation\nodetypes\CustomType:
    enabled: '1'
  verbb\navigation\nodetypes\PassiveType:
    enabled: '1'
  verbb\supertable\elements\SuperTableBlockElement:
    enabled: ''
    permissions: '*'
propagationMethod: all
siteSettings:
  0645712b-5f0e-4ede-b288-136194b2d349: # Karima Hočevar
    enabled: true
sortOrder: 1
structure:
  maxLevels: 2
  uid: e515de04-c6f2-4f25-8ed8-29bc52ad385b
