altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  aa95dd58-04ed-4253-9136-c34cb9ae57a0:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-03-13T21:34:46+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 114d34b5-8768-4ff8-a935-49f3c0d21043
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0357924e-066a-4206-94f9-ea29c8ae3bdb
        userCondition: null
fs: localFilesystem
handle: images
name: Images
sortOrder: 1
subpath: images
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: transforms
