columnSuffix: null
handle: description
instructions: null
name: Description
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: ''
  ckeConfig: 58e5b824-8237-4fc4-87f3-570c3969b621 # Simple
  createButtonLabel: null
  defaultTransform: null
  purifierConfig: null
  purifyHtml: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  sourceEditingGroups:
    - __ADMINS__
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
