columnSuffix: null
handle: imageSide
instructions: null
name: 'Image side'
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - 'Left side'
        -
          - value
          - left
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - 'Right side'
        -
          - value
          - right
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
