defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 05bbd45d-9ddc-4134-8cba-c41b83c3c23a # Page sections
handle: allInspirations
maxAuthors: 1
name: 'All inspirations'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  0645712b-5f0e-4ede-b288-136194b2d349: # Karima Hočevar
    enabledByDefault: true
    hasUrls: true
    template: index
    uriFormat: inspirations
type: single
