defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 096e6a68-e847-45c2-bfd7-9bb92635af8f # Event subscriber
handle: eventRegistrations
maxAuthors: 1
name: 'Event registrations'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  0645712b-5f0e-4ede-b288-136194b2d349: # Karima Hočevar
    enabledByDefault: true
    hasUrls: true
    template: event-registrations/_entry.twig
    uriFormat: 'event-registrations/{slug}'
type: channel
